#!/bin/bash
set -Ce

argv=${1:-}
script_dir=$(dirname $(readlink -f $0))

if [ "$argv" = "update" ]; then
    cd $script_dir && git pull  
    echo "update done"
# elif [ "$argv" = "install" ]; then
#     cd $script_dir && git clone https://github.com/takumiminami/tp_analysis.git
elif [ "$argv" = "uninstall" ]; then
    echo "The scripts of tpana will be deleted."
    read -p "Input y if you wish to delete all the scripts." flag
    if [ "$flag" = "y" ]; then
        cd $script_dir && git rm -rf . && cd .. && rm -rf tp_analysis
        echo "Uninstalliation completed"
    else
        echo "Aborted the uninstallation."
    fi
elif [ "$argv" = "" ]; then
    python3 $script_dir/main.py
else
    python3 $script_dir/main.py $argv 
fi

